#!/bin/bash -l
#SBATCH --job-name="test"
#SBATCH --account="uzh8"
#SBATCH --time=0:30:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=debug
#SBATCH --hint=nomultithread
#SBATCH --constraint=mc
##SBATCH --output=assignment_512.txt


export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun ./main > assignment_512.out
