#!/bin/bash -l
#SBATCH --job-name="test"
#SBATCH --account="uzg2"
#SBATCH --time=0:30:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=debug
#SBATCH --hint=nomultithread
#SBATCH --constraint=gpu
##SBATCH --output=GPU_Exercise_12_2_without_stream.txt


export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun ./exercise2 /store/uzh/uzh8/ESC412/ic_512.std 512 > GPU_Exercise_12_2_without_stream.out
